### cp8_11~13 예외 던지기(선언하기)

1. 예외 처리하기 (try_catch)

   1. printStackTrace() : 예외발생 당시의 호출스택에 있던 메서드 정보 + 예외메시지 출력

   2. getMessage() : 발생한 예외클래스의 인스턴스에 저장된 메세지 확인

   3. finally

2. 예외 발생시키기 (throw)
3. 예외 던지기

#### 예외 던지기

        void method() throws Exception1, Exception2 ... {

        }

##### 예외

###### 예외처리 해주지 않았을 경우

- 코드

        package cp8.ex8_9;

        public class Ex8_9 {
            public static void main(String[] args) throws Exception {
                method1();
                System.out.println("에러처리 끝!"); // 실행되지 않는다.
            }

            static void method1() throws Exception {
                method2();
            }

            static void method2() throws Exception {
                throw new Exception();
            }

        }

- 결과

        Exception in thread "main" java.lang.Exception
        at cp8.ex8_9.Ex8_9.method2(Ex8_9.java:12)
        at cp8.ex8_9.Ex8_9.method1(Ex8_9.java:8)
        at cp8.ex8_9.Ex8_9.main(Ex8_9.java:5)

###### 예외처리 해주었을 경우

- 코드

        package cp8.ex8_9;

        public class Ex8_9 {
            public static void main(String[] args) throws Exception {
                try {
                    method1();
                }
                catch(Exception e) {
                    e.printStackTrace();
                }
                System.out.println("에러처리 끝!");
            }

            static void method1() throws Exception {
                method2();
            }

            static void method2() throws Exception {
                throw new Exception();
            }
        }

- 결과

        java.lang.Exception
        at cp8.ex8_9.Ex8_9.method2(Ex8_9.java:20)
        at cp8.ex8_9.Ex8_9.method1(Ex8_9.java:16)
        at cp8.ex8_9.Ex8_9.main(Ex8_9.java:7)
        에러처리 끝!

- 설명

  - main 메서드가 method1 호출 -> method1이 method2 호출
  - method2 에서 Exception 에러 발생 시킨후 method1로 예외 던짐 -> method1는 main 메서드로 예외 던짐
  - main 메서드에서 예외처리를 해주지 않을 경우 : 예외가 비정상적으로 종료됨
  - main 메서드에서 예외처리를 해주었을 경우 : try-catch 문 종료후 다른 수행문 실행
